export enum ErrorMessages {
  InvalidDateFormat = "Invalid date format",
  InvalidEventIdFormat = "Invalid event id format",
  InvalidEventId = "No event found with this id",
  InvalidCategoryIds = "Invalid category ids",
  InvalidNextPageFormat = "Invalid nextPage format",
  InvalidSearchFormat = "Invalid search format",
  InvalidCharactersInSearch = "Invalid characters in search",
  EventIdIsRequired = "Event id is required",
  DateMustBeInTheFuture = "Date must be in the future",
  FromDateMustBeLessThanToDate = "'from' date must be before 'to' date",
  CityIsRequired = "City is required",
  CityNotValid = "City is not valid",
  CategoryIdsDoesntExists = "Category ids doesn't exists",
  SearchIsTooShort = "Search is too short",
  SearchIsTooLong = "Search is too long",
}
